
#' Check for batch effects
#'
#' Statistically tests for batch effects using the function
#' \code{\link[gPCA]{gPCA.batchdetect}}
#'
#' @param se \code{\link[SummarizedExperiment]{RangedSummarizedExperiment-class}}
#' object
#' @param assay Character or integer. Name or number of assay containing
#' expression data to be used for test of batch effects.
#' @param col.batch Character or integer. Column in colData() with batch
#' information (default: batch as generated by the function
#' \code{\link{define_batches}}.
#' @param filt Numeric. Parameter of the function
#' \code{\link[gPCA]{gPCA.batchdetect}} (default: NULL meaning no variance
#' filtering).
#' @param nperm Integer. Parameter of the function
#' \code{\link[gPCA]{gPCA.batchdetect}} (default: 1000 permutations for
#' empirical P value).
#' @param center Logical. Parameter of the function
#' \code{\link[gPCA]{gPCA.batchdetect}} (default: FALSE for uncentered
#' expression data).
#' @param scaleY Logical. Parameter of the function
#' \code{\link[gPCA]{gPCA.batchdetect}} (default: FALSE for no scaling by the
#' number of samples in each batch).
#' @param seed Integer. Parameter of the function
#' \code{\link[gPCA]{gPCA.batchdetect}} (default: 42 instead of NULL to make
#' function reproducible).
#'
#' @return see \code{\link[gPCA]{gPCA.batchdetect}}
#'
#' @importFrom gPCA gPCA.batchdetect
#' @export

check_batch_effects <- function(se,
                                assay = 1,
                                col.batch = "batch",
                                filt = NULL,
                                nperm = 1000,
                                center = FALSE,
                                scaleY = FALSE,
                                seed = 42) {

    if (is.character(assay) && !(assay %in% names(assays(se)))) {
        stop(paste("assay", assay, "not found!"))
    }

    res = gPCA.batchdetect(x = t(assays(se)[[assay]]),
                           batch = colData(se)[, col.batch],
                           filt = NULL)
    return(res)
}


#' Define batches based on scan date
#'
#' Groups samples into batches based on scan date. Samples run within a short
#' time interval can be defined to belong to the same batch.
#'
#' @param se \code{\link[SummarizedExperiment]{RangedSummarizedExperiment-class}}
#' object
#' @param col.scan.date Character or Integer. Column in colData() with scan
#' dates (default: scan.date as generated by the function
#' \code{\link{extract_scan_date}}.
#' @param diff.ignore Numeric. Time difference (in days) defined as negligible
#' (default: 1).
#'
#' @return \code{\link[SummarizedExperiment]{RangedSummarizedExperiment-class}}
#' object with batch information in additional column in colData()
#'
#' @export

define_batches <- function(se,
                           col.scan.date = "scan.date",
                           diff.ignore = 1) {

    scan.date = colData(se)[, col.scan.date]
    names(scan.date) = colnames(se)
    scan.date = sort(scan.date)
    diff = c(0, as.numeric(diff(scan.date)))
    diff[diff == diff.ignore] = 0
    batch = as.numeric(as.factor(cumsum(diff)))
    names(batch) = names(scan.date)
    se$batch = batch[colnames(se)]
    return(se)
}


