
## log transformed data

#' Identification of duplicated samples
#'
#' Detects duplicated samples with extremely high correlation of expression
#' values using the function \code{\link[doppelgangR]{doppelgangR}}.
#'
#' @param se \code{\link[SummarizedExperiment]{RangedSummarizedExperiment-class}}
#' object
#' @param assay Character or integer. Name or number of assay containing
#' log transformed expression values.
#' @param corFinder.args List. Parameter of the function
#' \code{\link[doppelgangR]{doppelgangR}} (default: do not use
#' \code{\link[sva]{ComBat}} function for batch correction).
#' @param plot Logical. Should histogram of pairwise correlations be plotted?
#' (default: FALSE).
#' @param ... Additional arguments passed to the
#' \code{\link[doppelgangR]{doppelgangR}} function.
#'
#' @return data.frame with information about duplicated samples (as generated by
#' summary function of \code{\link[doppelgangR]{DoppelGang-class}}) or NULL
#'
#' @import doppelgangR
#' @importFrom methods as
#' @export

detect_duplicated_samples <- function(se,
                                      assay = 1,
                                      corFinder.args = list(use.ComBat =
                                                                FALSE),
                                      plot = FALSE,
                                      ...) {

    ## convert to ExpressionSet using only specified assay
    if (is.character(assay) && !(assay %in% names(assays(se)))) {
        stop(paste("assay", assay, "not found!"))
    }
    expr = assays(se)[[assay]]

    se.red = se
    assays(se.red) = list(exprs = expr)
    eset = as(se.red,
              "ExpressionSet")

    res = doppelgangR(eset,
                      corFinder.args = corFinder.args,
                      phenoFinder.args = NULL,
                      verbose = FALSE,
                      cache.dir = NULL,
                      intermediate.pruning = TRUE)
    res.sum = summary(res)

    if (plot) {
        plot(res)
    }

    if (nrow(res.sum) > 0) {
        return(res.sum)
    } else {
        return(NULL)
    }
}
